version: '3.2'

services:

  db:
    image: mysql
    restart: always
    ports:
      - ${DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080